#!/bin/sh

# Basic support for the Linux Standard Base Specification 3.1.0
### BEGIN INIT INFO
# Provides: rdiff_web
# Required-Start: $network $local_fs
# Required-Stop: $network
# Default-Start: 2 3 5
# Default-Stop: 0 6
# Description: Manages the rdiffWeb daemon
### END INIT INFO

PIDFILE="/var/run/rdiff-web"

SUCCESS_MSG="[71G done"
ERROR_MSG="[71Gfailed"

if [ -f /etc/init.d/functions ]; then
 . /etc/init.d/functions
fi

# This script won't be able to run without root privileges.
if [ `id -u` -ne 0 ]; then
   echo "Error: this script must be run as root."
   exit 1
fi

# Used a lot; is rdiff-web running?
status() {
    if [ -e "$PIDFILE" ]; then
	PIDLIST=""
        for tmp in `cat $PIDFILE` 
	do 
	    PID=`ps -fp $tmp | awk '/rdiff-web/ {print $2}'`;    
	    if [ "$PID" ]; then
		echo $PID
		return 
	    fi
	done
    fi	
    echo 0
}

# See how we were called.
case "$1" in
   start)
      if [ ! -f /etc/rdiffweb/rdw.conf ]; then
         echo -n "rdiffWeb is not configured!  Please run 'rdiff-web-config'."
         echo $ERROR_MSG
         exit 1
      fi
      echo -n "Starting rdiffWeb..."
      /usr/bin/rdiff-web --pid-file="$PIDFILE" \
      --background > /dev/null 2>&1
      EXIT_CODE=$?
      if [ $EXIT_CODE -ne 0 ] ; then
       echo -n "rdiffweb did not startup (Exit code $EXIT_CODE) "
       echo $ERROR_MSG
       exit 1
      fi
      PID=$(status)
      if [ "$PID" -eq 0 ]; then
       echo  -n "rdiffweb is not running! "
       echo $ERROR_MSG
       exit 1
      fi
      echo -n " running as PID $PID."
      echo $SUCCESS_MSG
      exit 0
   ;;

   stop)
      if [ -e "$PIDFILE" ]; then
         echo -n "Stopping rdiffWeb..."
         kill `cat "$PIDFILE" 2>/dev/null` > /dev/null 2>&1
	 for loop in 0 1 2 3 4 5 6 7 8 9; do
	     PID=$(status)
	     if [ "$PID" -eq 0 ]; then
		 rm $PIDFILE > /dev/null 2>&1
		 echo $SUCCESS_MSG
		 exit 0
	     else
		 echo -n " ."
		 sleep 1
	     fi 
	 done
	 echo -n "rdiffweb will not stop!"
	 echo $ERROR_MSG
	 exit 1
      else
         echo -n "rdiffWeb is not running"
         echo $ERROR_MSG
         exit 1
      fi
   ;;

   status)
      echo -n "rdiffWeb "
      PID=$(status)
      if [ "$PID" -ne 0 ]; then
         echo "is running as PID $PID."
         exit 0
      else
         echo "is not running."
         exit 1
      fi
   ;;

   restart)
      "$0" stop && "$0" start
   ;;

   *)
      echo "Usage: `basename "$0"` {start|stop|status|restart}"
      exit 1
esac

exit 0
